-- DROP TABLE INGENIO.TAMANOGRANODETALLE;
-- DROP TABLE INGENIO.TAMANOGRANO;

-- HSQLDB
-- TRUNCATE SCHEMA INGENIO AND COMMIT;

-- PostgreSQL
--DROP SCHEMA ingenio CASCADE;

DROP TABLE ingenio.blcdetalle1;
DROP TABLE ingenio.blc;
