-- DROP TABLE INGENIO.CANADETALLE1;
-- DROP TABLE INGENIO.CANA;
-- DROP TABLE INGENIO.MELADURADETALLE;
-- DROP TABLE INGENIO.MELADURA;
-- DROP TABLE INGENIO.TURBIEDADDETALLE1;
-- DROP TABLE INGENIO.TURBIEDAD;
DROP TABLE INGENIO.MASASDETALLE1;
DROP TABLE INGENIO.MASASDETALLE2;
DROP TABLE INGENIO.MASASDETALLE3;
DROP TABLE INGENIO.MASASDETALLE4;
DROP TABLE INGENIO.MASAS;

-- TRUNCATE SCHEMA INGENIO AND COMMIT;

