-- SELECT * FROM ingenio.PARO;
-- SELECT * FROM ingenio.PARO_DETALLES;

-- SELECT * FROM ingenio.TRASH;
-- SELECT * FROM ingenio.TRASHDETALLE;

-- SELECT ID, HORA, CALPORCAZURED FROM ingenio.TRASHCANADETALLE2;
-- SELECT * FROM ingenio.TRASHCANADETALLE2;
-- SELECT * FROM INGENIO.MELADURADETALLE;
-- SELECT * FROM INGENIO.DIATRABAJO; 

-- SELECT * FROM INGENIO.COLORMATDETALLE;
-- SELECT * FROM INGENIO.COLORMAT;
-- SELECT * FROM INGENIO.TAMANOGRANODETALLE;
SELECT * FROM ingenio.cto24h;
SELECT * FROM ingenio.cto24hdetalle1;
SELECT * FROM ingenio.cto24hdetalle2;
SELECT * FROM ingenio.cto24hdetalle3;
