-- SELECT * FROM ingenio.PARO;
-- SELECT * FROM ingenio.PARO_DETALLES;

-- SELECT * FROM ingenio.TRASH;
-- SELECT * FROM ingenio.TRASHDETALLE;

-- SELECT ID, HORA, CALPORCAZURED FROM ingenio.TRASHCANADETALLE2;
-- SELECT * FROM ingenio.TRASHCANADETALLE2;
-- SELECT * FROM INGENIO.MELADURADETALLE;
-- SELECT * FROM INGENIO.DIATRABAJO; 

--SELECT * FROM INGENIO.COLORMATDETALLE;
SELECT * FROM INGENIO.COLORMAT;
