-- DROP TABLE ingenio.PARO_DETALLES;
-- DROP TABLE ingenio.PARO;
-- DROP TABLE ingenio.JUGO_DETALLES;
-- DROP TABLE ingenio.JUGO;

-- DROP TABLE ingenio.STOCKFABRICA;
-- DROP TABLE ingenio.TRASHCANA;
-- DROP TABLE ingenio.DIATRABAJO;

TRUNCATE SCHEMA INGENIO AND COMMIT;

