-- DROP TABLE ingenio.PARO_DETALLES;
-- DROP TABLE ingenio.PARO;
-- DROP TABLE ingenio.JUGO_DETALLES;
-- DROP TABLE ingenio.JUGO;

-- DROP TABLE ingenio.STOCKFABRICA;
-- DROP TABLE ingenio.TRASHCANA;
-- DROP TABLE ingenio.DIATRABAJO;

-- DROP TABLE INGENIO.TRASHCANADETALLE2;
-- DROP TABLE INGENIO.TRASHCANADETALLE1;
-- DROP TABLE INGENIO.TRASHCANA;

-- DELETE FROM INGENIO.TRASHDETALLE;
-- DELETE FROM INGENIO.TRASH;

DELETE FROM ingenio.cto24hdetalle3;
DELETE FROM ingenio.cto24hdetalle2;
DELETE FROM ingenio.cto24hdetalle1;
DELETE FROM ingenio.cto24h;
