INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('063', 'Tanque Jugo Diluido', 'tanJugDil');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('064', 'Tanque de Jugo Claro', 'tanJugCla');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('065', 'Tanque Jugo Encalado', 'tanJugEnc');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('066', 'Tanque Jugo Filtrado', 'tanJugFil');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('067', 'Clarificador de Jugo', 'claJug');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('068', 'Torre Sulfitación Jugo', 'torSulJug');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('069', 'Torre Sulfitacón Meladura', 'torSulMel');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('070', 'Calentador Jugo Claro', 'calJugCla');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('071', 'Calentadores de Jugo', 'calJug');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('072', 'Evaporador I', 'eva1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('073', 'Evaporador II', 'eva2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('074', 'Evaporador III', 'eva3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('075', 'Semillero B-II', 'sem4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('076', 'Evaporador IVA', 'eva4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('077', 'Evaporador IV', 'eva5');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('078', 'Tanque Meladura Cruda', 'tanMelCru');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('079', 'Calentador Meladura', 'calMel');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('080', 'Clarificador Meladura', 'claMel');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('081', 'Vaso Reacción', 'vasRea');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('082', 'Tacho Nº 1', 'tac1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('083', 'Tacho Nº 2', 'tac2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('084', 'Tacho Nº 3', 'tac3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('085', 'Tacho Nº 4', 'tac4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('086', 'Tanque Meladura I', 'tanMel1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('087', 'Tanque Meladura II', 'tanMel2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('088', 'Tanque Meladura III-30', 'tanMel3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('089', 'Tanque Fundidor I', 'tanFun1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('090', 'Tanque Fundidor II', 'tanFun2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('091', 'Tanque Miel A I Grande', 'tanMie1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('092', 'Tanque Miel A II Pequeño', 'tanMie2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('093', 'Tanque Miel B', 'tanMie3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('094', 'Tanque Miel-Rep', 'tanMie4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('095', 'Tanque Prep Mieles', 'tanPreMie');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('096', 'Tanque Miel CL-MRep', 'tanMieClM');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('097', 'Semillero A', 'sem1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('098', 'Semillero B', 'sem2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('099', 'Semillero C', 'sem3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('100', 'Recibidor Magma B-II', 'recMag2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('101', 'Recibidor Masa A I', 'recMas1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('102', 'Recibidor Masa A II', 'recMas2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('103', 'Recibidor Masa B I', 'recMas3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('104', 'Recibidor Masa B II', 'recMas4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('105', 'Recibidor Masa C', 'recMas5');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('106', 'Recibidor Masa C-II', 'recMas6');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('107', 'Alimentador Centrífuga MA', 'aliCen1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('108', 'Alimentador Centrífuga MB', 'aliCen2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('109', 'Alimentador Centrífuga Repurg', 'aliCen3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('110', 'Alimentador Centrífuga MC', 'aliCen4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('111', 'Recibidor Magma B I', 'recMag1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('112', 'Recibidor Magma Rep', 'recMag3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('113', 'Recibidor Magma C', 'recMag4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('114', 'Recibidor Terrón FS', 'recTer');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('115', 'Recibidor Miel A I', 'recMie1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('116', 'Recibidor Miel A II', 'recMie2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('117', 'Recibidor Miel B', 'recMie3');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('118', 'Recibidor Miel Rep', 'recMie4');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('119', 'Fundidor I Viejo', 'funVie1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('120', 'Fundidor II Nuevo', 'funNue2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('121', 'Cristaliz Vertical', 'criVer');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('122', 'Tolva 50 Kg Nº 1', 'tol50K1');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('123', 'Tolva 50 Kg Nº 2', 'tol50K2');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('124', 'Tolva Familiar Nº 3', 'tolFam');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('001', 'CAÑA/DIA', 'canaDia');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('002', 'AGUA MACERACION', 'aguaM');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('003', 'JUGO DILUIDO (BR)', 'jDiluidoBr');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('004', 'BAGAZO (CALCULADO)', 'bagazoC');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('005', 'BAGAZO (DIRECTO)', 'bagazoD');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('006', 'CACHAZA', 'cachaza');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('007', 'MIEL FINAL MELAZA', 'mielFM');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('008', 'AZUCAR BLANCA', 'azucarB');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('009', 'CAÑA NETA', 'canaNeta');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('010', 'JUGO NETO', 'jugoNeto');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('011', 'MELADURA', 'meladura');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('012', 'HOJA DE CAÑA', 'hojaCana');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('013', 'SACOS DISUELTOS', 'sacosD');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('014', 'BX J. CLARO', 'jClaroB');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('015', 'SALIDA EVAP I', '');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('016', 'SALIDA EVAP II', '');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('017', 'SALIDA EVAP III', '');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('018', 'SALIDA EVAP IV', '');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('019', 'TRASH', 'trash');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('020', 'BRIX CAÑA (DAC)', 'brixCanaDac');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('021', 'SAC CAÑA (DAC)', 'sacCanaDac');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('022', 'PZA CAÑA (DAC)', 'pzaCanaDac');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('023', 'FIBRA CAÑA', 'fibCana');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('024', 'HUM CAÑA', 'humCana');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('025', 'BRIX CAÑA', 'brixCana');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('026', 'SAC CAÑA', 'sacCana');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('027', 'PZA CAÑA', 'pzaCana');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('028', 'SAC JUGO BR %CAÑA EXTRAIDA', 'sacJBrCanaExtraida');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('029', 'SAC BAGAZO', 'sacBagazo');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('030', 'FIBRA BAGAZO', 'fibBagazo');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('031', 'HUM BAGAZO', 'humBagazo');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('032', 'BRIX BAGAZO', 'brixBagazo');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('033', 'PODER CAL', 'podCal');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('034', 'CENIZAS (seca)', 'cenSeca');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('035', 'BRIX M.F', 'brixMf');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('036', 'SAC M.F', 'sacMf');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('037', 'PZA M.F', 'pzaMf');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('038', 'CENIZA M.F', 'cenMf');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('039', 'AR/ASH', 'arAsh');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('040', 'Gal/TCM', 'galTcm');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('041', 'ρ JUGO DILUIDO', 'rhoJugDil');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('042', 'SOLIDOS INSOL', 'solInsol');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('043', 'FOSFATOS', 'fosfatos');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('044', 'BRIX J.DIL', 'brixJDil');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('045', 'SAC J.DIL', 'sacJDil');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('046', 'PZA J.DIL', 'pzaJDil');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('047', 'POL CACHAZA', 'polCachaza');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('048', 'RATA EVAP', 'rataEvap');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('049', 'I,P', 'ip');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('050', 'TURBIEDAD', 'turbiedad');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('051', 'BRIX J. CLARO', 'brixJClaro');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('052', 'SAC J. CLARO', 'sacJClaro');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('053', 'PZA J. CLARO', 'pzaJClaro');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('054', 'BRIX J.P.EX', 'brixJPEx');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('055', 'SAC J.P.EX', 'sacJPEx');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('056', 'PZA J.P.EX', 'pzaJPEx');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('057', 'BRIX J. RES', 'brixJRes');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('058', 'SAC J.RES', 'sacJRes');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('059', 'PZA J. RES', 'pzaJRes');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('060', 'COLOR', 'color');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('061', 'POL AZUCAR', 'polAzucar');
INSERT INTO ingenio.ingenio.material("id", descripcion, campo) VALUES ('062', 'HUMEDAD', 'humedad');
