-- https://wordcounter.net/random-word-generator
-- https://www.random.org/integers/

insert into 
	topic (name) 
values
	('programming'),
	('humor'),
	('science'),
	('fact'),
	('frogs'),
	('steel'),
	('dirt'),
	('knee'),
	('clocks'),
	('oil'),
	('sugar'),
	('sky'),
	('silver'),
	('selection'),
	('trains'),
	('gate'),
	('humor'),
	('meat'),
	('beef'),
	('position'),
	('mouth'),
	('brother'),
	('noise'),
	('rub'),
	('time'),
	('stem'),
	('berry'),
	('goat'),
	('brain'),
	('science'),
	('drawer'),
	('skirt'),
	('breakfast'),
	('orange'),
	('basin'),
	('brake'),
	('shock'),
	('island'),
	('twig'),
	('clouds');

insert into 
	post (topic_id,title,text) 
values
	(20,'infringe','bashful'),
	(1,'suggest','poised'),
	(19,'sneeze','second'),
	(4,'shatter','fertile'),
	(20,'knit','hissing'),
	(1,'count','clear'),
	(8,'board','messy'),
	(11,'decrease','bumpy'),
	(33,'oppress','plant'),
	(6,'encroach','pleasant'),
	(18,'tread','misty'),
	(1,'propose','ad hoc'),
	(4,'scold','mammoth'),
	(35,'scan','tasty'),
	(1,'pause','extra-large'),
	(39,'damp','humorous'),
	(2,'soar','zonked'),
	(20,'sally','quixotic'),
	(20,'shit','thoughtless'),
	(20,'have','feeble'),
	(1,'root','crazy'),
	(20,'have','hilarious'),
	(9,'count','black'),
	(35,'roll','fine'),
	(1,'comment','mellow'),
	(1,'encourage','resolute'),
	(9,'nail','aboriginal'),
	(9,'state','pleasant'),
	(9,'qualify','merciful'),
	(9,'fight','devilish');