DROP TABLE IF EXISTS CLIENTE;
  
CREATE TABLE CLIENTE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(250),
  APELLIDO VARCHAR(250)
);

DROP TABLE IF EXISTS ARTICULO;
  
CREATE TABLE ARTICULO(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(250),
  PRECIO NUMERIC(6,2)
);

CREATE TABLE ORDEN(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CLIENTE_ID BIGINT NOT NULL,
  ARTICULOS VARCHAR(250),
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);