package ec.carper.ingenio.test

import org.openxava.tests.*

class FlujoJugoTest extends ModuleTestBase {

    FlujoJugoTest(String testName) {
        super(testName, "Ingenio", "FlujoJugo")
    }
    
    void testCrear() throws Exception {
        login("admin", "admin")
        
        execute("CRUD.new")
        
        setValue("diaTrabajo.id" , Aux.instance.diaTrabajoId)
        setValue("descripcion"   , "JUNIT")
        execute ("Ingenio.save")
        assertNoErrors()
    
        setConditionValues("JUNIT")
        setConditionComparators("contains_comparator")
        execute("List.filter")
        //printHtml()
        execute("List.viewDetail", "row=0"); // Pulsamos en la primera fila
        assertCollectionRowCount("detalle", 0) // La colección esta vacía 

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "07:30")
        assertValue ( "hora"          , "07/08/2019 07:30")
        setValue    ( "ini"           , "0")
        setValue    ( "fin"           , "2061")
        assertValue ( "tot"           , "2061")
        setValue    ( "horaSBrixJDil" , "06:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 06:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "2,057.296383")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "08:30")
        assertValue ( "hora"          , "07/08/2019 08:30")
        setValue    ( "ini"           , "2061")
        setValue    ( "fin"           , "2081")
        assertValue ( "tot"           , "20")
        setValue    ( "horaSBrixJDil" , "06:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 06:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "19.964060")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "09:30")
        assertValue ( "hora"          , "07/08/2019 09:30")
        setValue    ( "ini"           , "2081")
        setValue    ( "fin"           , "21")
        assertValue ( "tot"           , "-2060")
        setValue    ( "horaSBrixJDil" , "06:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 06:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "-2,056.298180")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "10:30")
        assertValue ( "hora"          , "07/08/2019 10:30")
        setValue    ( "ini"           , "21")
        setValue    ( "fin"           , "2120")
        assertValue ( "tot"           , "2099")
        setValue    ( "horaSBrixJDil" , "08:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 08:00")
        assertValue ( "brixJDil"      , "13.41")
        assertValue ( "p"             , "1,052.344")
        assertValue ( "tonJugo"       , "2,208.870056")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "11:30")
        assertValue ( "hora"          , "07/08/2019 11:30")
        setValue    ( "ini"           , "2120")
        setValue    ( "fin"           , "2140")
        assertValue ( "tot"           , "20")
        setValue    ( "horaSBrixJDil" , "08:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 08:00")
        assertValue ( "brixJDil"      , "13.41")
        assertValue ( "p"             , "1,052.344")
        assertValue ( "tonJugo"       , "21.046880")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "12:30")
        assertValue ( "hora"          , "07/08/2019 12:30")
        setValue    ( "ini"           , "2140")
        setValue    ( "fin"           , "2160")
        assertValue ( "tot"           , "20")
        setValue    ( "horaSBrixJDil" , "08:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 08:00")
        assertValue ( "brixJDil"      , "13.41")
        assertValue ( "p"             , "1,052.344")
        assertValue ( "tonJugo"       , "21.046880")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "13:30")
        assertValue ( "hora"          , "07/08/2019 13:30")
        setValue    ( "ini"           , "2160")
        setValue    ( "fin"           , "2179")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "10:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 10:00")
        assertValue ( "brixJDil"      , "13.56")
        assertValue ( "p"             , "1,052.768")
        assertValue ( "tonJugo"       , "20.002592")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "14:30")
        assertValue ( "hora"          , "07/08/2019 14:30")
        setValue    ( "ini"           , "2179")
        setValue    ( "fin"           , "2198")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "10:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 10:00")
        assertValue ( "brixJDil"      , "13.56")
        assertValue ( "p"             , "1,052.768")
        assertValue ( "tonJugo"       , "20.002592")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "15:30")
        assertValue ( "hora"          , "07/08/2019 15:30")
        setValue    ( "ini"           , "2198")
        setValue    ( "fin"           , "2216")
        assertValue ( "tot"           , "18")
        setValue    ( "horaSBrixJDil" , "10:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 10:00")
        assertValue ( "brixJDil"      , "13.56")
        assertValue ( "p"             , "1,052.768")
        assertValue ( "tonJugo"       , "18.949824")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "16:30")
        assertValue ( "hora"          , "07/08/2019 16:30")
        setValue    ( "ini"           , "2216")
        setValue    ( "fin"           , "2235")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "12:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 12:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "18.965857")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "17:30")
        assertValue ( "hora"          , "07/08/2019 17:30")
        setValue    ( "ini"           , "2235")
        setValue    ( "fin"           , "2252")
        assertValue ( "tot"           , "17")
        setValue    ( "horaSBrixJDil" , "12:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 12:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "16.969451")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "18:30")
        assertValue ( "hora"          , "07/08/2019 18:30")
        setValue    ( "ini"           , "2252")
        setValue    ( "fin"           , "2271")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "12:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 12:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "18.965857")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "19:30")
        assertValue ( "hora"          , "07/08/2019 19:30")
        setValue    ( "ini"           , "2271")
        setValue    ( "fin"           , "2290")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "14:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 14:00")
        assertValue ( "brixJDil"      , "13.86")
        assertValue ( "p"             , "1,054.041")
        assertValue ( "tonJugo"       , "20.026779")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "20:30")
        assertValue ( "hora"          , "07/08/2019 20:30")
        setValue    ( "ini"           , "2290")
        setValue    ( "fin"           , "2309")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "14:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 14:00")
        assertValue ( "brixJDil"      , "13.86")
        assertValue ( "p"             , "1,054.041")
        assertValue ( "tonJugo"       , "20.026779")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "21:30")
        assertValue ( "hora"          , "07/08/2019 21:30")
        setValue    ( "ini"           , "2309")
        setValue    ( "fin"           , "2329")
        assertValue ( "tot"           , "20")
        setValue    ( "horaSBrixJDil" , "14:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 14:00")
        assertValue ( "brixJDil"      , "13.86")
        assertValue ( "p"             , "1,054.041")
        assertValue ( "tonJugo"       , "21.080820")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "22:30")
        assertValue ( "hora"          , "07/08/2019 22:30")
        setValue    ( "ini"           , "2329")
        setValue    ( "fin"           , "2349")
        assertValue ( "tot"           , "20")
        setValue    ( "horaSBrixJDil" , "16:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 16:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "19.964060")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "23:30")
        assertValue ( "hora"          , "07/08/2019 23:30")
        setValue    ( "ini"           , "2349")
        setValue    ( "fin"           , "2366")
        assertValue ( "tot"           , "17")
        setValue    ( "horaSBrixJDil" , "16:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 16:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "16.969451")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "00:30")
        assertValue ( "hora"          , "08/08/2019 00:30")
        setValue    ( "ini"           , "2366")
        setValue    ( "fin"           , "2387")
        assertValue ( "tot"           , "21")
        setValue    ( "horaSBrixJDil" , "16:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 16:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "20.962263")
        execute("Collection.save")

        execute('Collection.new' , 'viewObject=xava_view_section0_detalle')
        assertDialog()
        setValue    ( "horaS"         , "01:30")
        assertValue ( "hora"          , "08/08/2019 01:30")
        setValue    ( "ini"           , "2387")
        setValue    ( "fin"           , "2406")
        assertValue ( "tot"           , "19")
        setValue    ( "horaSBrixJDil" , "18:00")
        assertValue ( "horaBrixJDil"  , "07/08/2019 18:00")
        assertValue ( "brixJDil"      , "0.00")
        assertValue ( "p"             , "998.203")
        assertValue ( "tonJugo"       , "18.965857")
        execute("Collection.save")
        
        assertNoErrors()
        // **************************************************
        // FINALIZAR
        execute    ("CRUD.delete")
        assertNoErrors()
    }

}   
