## Rest Client tests

### Create User
POST http://localhost:8080/user/add
Content-Type: application/json

{
  "email": "cjperez@nisum.com",
  "name": "Carlos Julio Pérez",
  "password": "secret",
  "phones": [
    {
      "citycode": 1,
      "countrycode": 57,
      "number": 123123
    }
  ]
}

### Get Users
GET http://localhost:8080/user/all

### Get single record
GET http://localhost:8080/user/find/1